#!/bin/bash


REFERENCE_LIB_PATH=$1
KMER_SIZE=31
TAXONOMY_TREE_PATH=$2
DESPI_BIN_PATH=$3
INDEX_DIR=$4

USAGE="
`basename $0` <REF_DIR> <NODE_PATH> <DESPI_BIN_DIR> <INDEX_DIR>

ARGUMENT
    <REF_DIR>                directory of reference library.
    <NODE_PATH>              location of nodes.dmp file.
    <DESPI_BIN_DIR>          directory of deSPI execuative files.
    <INDEX_DIR>              directory to store deSPI's index.
"
if [ $# -lt 4 ]
then
	echo "ERROR: Parameters are not enough"
	printf "$USAGE"
	exit 1
fi

check_for_jellyfish() {
	JELLYFISH_VERSION=$(jellyfish --version | awk '{print $2}')	
 	echo $JELLYFISH_VERSION
	if [[ $JELLYFISH_VERSION =~ ^1\. ]]
	then
		return `true`
	else
		return `false`
	fi	
}

TRANSIT=transit


if check_for_jellyfish
then
	find $REFERENCE_LIB_PATH/ -name '*.fna' | xargs -n 1 cat > deSPI-wgs.fa
	FILE_SIZE=$(ls -l deSPI-wgs.fa | awk '{print $5}')
	echo $FILE_SIZE		
	let JELLYFISH_HASH_SIZE=FILE_SIZE*115/100
	echo $JELLYFISH_HASH_SIZE	
	mkdir -p $TRANSIT 
       	cd $TRANSIT

	jellyfish count -m $KMER_SIZE -s $JELLYFISH_HASH_SIZE -t 4 ../deSPI-wgs.fa
	
	if [ -e "mer_counts_1" ]
	then
		echo hahahha
		jellyfish merge -o database.jdb.tmp mer_counts_*
	else
		mv mer_counts_0 database.jdb.tmp
	fi
	mv database.jdb.tmp ../database.jdb

	cd ..

	rm -rf $TRANSIT


	if [ -f "$DESPI_BIN_PATH/deSPI-sort" ]
	then
		$DESPI_BIN_PATH/deSPI-sort database.jdb $KMER_SIZE
		rm -f database.jdb
	else
		echo "deSPI-index requires deSPI-sort"
		exit 1
	fi
	
	if [ -f "$DESPI_BIN_PATH/deSPI" ]
	then
		$DESPI_BIN_PATH/deSPI index database.srt $TAXONOMY_TREE_PATH deSPI-wgs.fa $INDEX_DIR
	else
		echo "deSPI-index requires deSPI"
	fi	
	rm -f deSPI-wgs.fa database.srt
	cp $TAXONOMY_TREE_PATH $INDEX_DIR/map
else 
	echo "deSPI requires jellyfish version 1"
	exit 1

fi	

cd ..



